const REGISTER_USER = "REGISTER_USER";
const UPDATE_USER_IN_LIST = "UPDATE_USER_IN_LIST";
// const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
// const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export default {
	REGISTER_USER,
	UPDATE_USER_IN_LIST
};
